### ISSUE TITLE
Using Global CSS

### ISSUE THREAD

**Issue by Quadriphobs1** [pedronauck/docz-plugin-css#13]
Is there a way to use a global css scope based, I am having a global css for my project with `scss` which my project auto detect the compiled css and append it to the head, but I can't seems to get a way to work with this on my project. The problem is that I am not using css modules so its not going to work, is there an option to use this without css module and having a global scope styles, I dig into the styling and I see that the compiled styles if I import `import '../styles/scss/styles.scss'` in my `document.mdx` file it usually append on the class names with `.docz_...`

**Comment by nurycaroline** [comment]
Hi @Quadriphobs1 

In doczrc.js, use ```cssmodules: false```, Solved for me.

```
import { css } from 'docz-plugin-css'

export default {
  title: 'CSS Sass',
  plugins: [
    css({
      preprocessor: 'sass',
      cssmodules: false,
    }),
  ],
}
```

**Comment by Quadriphobs1** [comment]
👍
