### ISSUE TITLE
Cannot output any css when build docz

### ISSUE THREAD

**Issue by PeterRock** [pedronauck/docz-plugin-css#26]
Add a class `hello-can-you-see-me` for `a`.
### js:
<img width="554" alt="js" src="https://user-images.githubusercontent.com/17565091/65825806-f3dbd200-e2ad-11e9-9e85-f3722c8cd421.png">

### css:
<img width="185" alt="css" src="https://user-images.githubusercontent.com/17565091/65825809-fccca380-e2ad-11e9-8d21-44423b6f15b5.png">

### dev mode preview (docz dev): 
as you see, it works perfect!
<img width="336" alt="WX20190929-113230@2x" src="https://user-images.githubusercontent.com/17565091/65825822-22f24380-e2ae-11e9-9130-f3fe817f0d10.png">

### build mode preview (docz build):
there is no css file in the `dist` folder, and it can not work.
<img width="311" alt="build preview" src="https://user-images.githubusercontent.com/17565091/65825840-5df47700-e2ae-11e9-8d80-1a7c7bec55f8.png">

### check the output files
<img width="255" alt="folders" src="https://user-images.githubusercontent.com/17565091/65825876-cf342a00-e2ae-11e9-9b29-31f9660deebe.png">

------
 I cannot figure out what happend for this.
 I just found diff from here
<img width="451" alt="diff" src="https://user-images.githubusercontent.com/17565091/65825958-ba0bcb00-e2af-11e9-9a7d-d11358cd6672.png">

**Comment by trybick** [comment]
Are you on docz v2? I believe the `docz-plugin-css` plugin is only for docz v1

https://www.docz.site/docs/usage-with-css-preprocessors

**Comment by albyrock87** [comment]
Hi, I'm using docz v2 and this issue is still there.. @PeterRock did you manage to solve this?

**Comment by PeterRock** [comment]
I give up now
