### ISSUE TITLE
Unparseable filetype scss

### ISSUE THREAD

**Issue by SimonErich** [pedronauck/docz-plugin-css#8]
Hey,

thanks for this awesome package.
I'm having an issue with my next.js, React + typescript + scss-modules application.

it works perfectly on simple components, but I always get an error in components with scss files.

**This is the error on dev:**
`Could not create Open in CodeSandbox Error: unparseable filetype: .scss for file ...`

**This is what my component looks like:**

        import * as React from 'react';
	import { ReactChild } from 'react';
	import * as styles from './Col.scss';
	
	interface IColProps {
	  children: ReactChild,
	  size: number,
	  width: string|number,
	}
	
	class Col extends React.Component<IColProps, {}> {
	  public render () {
	    const { children, size, width } = this.props;
	
	    return (
	      <div className={styles.col} style={{ flexGrow: size, minWidth: width }}>
	        {children}
	      </div>
	    );
	  }
	}
	
	export default Col;

I've installed this plugin and also added it to my doczrc.js:
	import { css } from 'docz-plugin-css'
	
	module.exports = {
		title: 'Test doc',
		typescript: true,
		plugins: [
			css({
				preprocessor: 'sass',
				cssmodules: true,
			})
		]
	};

**Comment by pedronauck** [comment]
Try to update your docz version, this will be fixed in the newests version :)
